language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO=1.5
  - DJANGO=1.6
install:
  - pip install -r requirements.txt --use-mirrors
script:
  - python tests/manage.py test rated --settings=settings
